server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: appnotes
          uri: http://localhost:8080/
          predicates:
            - Path=/appnotes/**