server:
  port: 8765

spring:
  application:
    name: appnotes
management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  endpoint:
    health:
      show-details: "ALWAYS"
